version: '2'

services:

  splunk_master:
    image: "splunk/splunk"
    hostname: splunk_master
    environment:
      SPLUNK_START_ARGS: --accept-license --answer-yes
      SPLUNK_CMD_1: 'add user super -password password -role admin -auth admin:changeme'
    ports:
     - "8001:8000"
    volumes:
     - ./apps/my_master_app:/opt/splunk/etc/apps/my_master_app

  splunk_head:
    image: "splunk/splunk"
    hostname: splunk_head_01
    environment:
      SPLUNK_START_ARGS: --accept-license --answer-yes
      SPLUNK_CMD_1: 'add user super -password password -role admin -auth admin:changeme'
    ports:
     - "8000:8000"
    volumes:
     - ./apps/my_app:/opt/splunk/etc/apps/my_app

  splunk_indexer_1:
    image: "splunk/splunk"
    hostname: splunk_idx_01
    environment:
      SPLUNK_START_ARGS: --accept-license --answer-yes
      SPLUNK_ENABLE_LISTEN: 9997
      SPLUNK_CMD_1: 'add user super -password password -role admin -auth admin:changeme'
    ports:
      - "8021:8000"

  splunk_indexer_2:
    image: "splunk/splunk"
    hostname: splunk_idx_02
    environment:
      SPLUNK_START_ARGS: --accept-license --answer-yes
      SPLUNK_ENABLE_LISTEN: 9997
      SPLUNK_CMD_1: 'add user super -password password -role admin -auth admin:changeme'
    ports:
      - "8022:8000"

  splunk_indexer_3:
    image: "splunk/splunk"
    hostname: splunk_idx_03
    environment:
      SPLUNK_START_ARGS: --accept-license --answer-yes
      SPLUNK_ENABLE_LISTEN: 9997
      SPLUNK_CMD_1: 'add user super -password password -role admin -auth admin:changeme'
    ports:
      - "8023:8000"
